#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_WINDOW_WIDTH    1280
#define DEFAULT_WINDOW_HEIGHT   720

float WINDOW_WIDTH  =  DEFAULT_WINDOW_WIDTH;
float WINDOW_HEIGHT =  DEFAULT_WINDOW_HEIGHT;

#endif